---
galaxy_info:
  role_name: ludus_ad_group_add_member
  author: badsectorlabs
  description: Add an ad group to another
  company: Bad Sector Labs
  license: AGPL-3.0-or-later
  min_ansible_version: "2.14"
  platforms:
    - name: Windows
      versions:
        - 2019
        - 2022
  galaxy_tags:
    - windows
    - active_directory
    - ludus
    - gmsa
    - dsc
    - service_account

dependencies: []
